name: Deploy

on:
  push:
    branches: 
      - deploy
      - public-main
  pull_request:
    branches: 
      - deploy
      - public-main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SATELLITE_ID_DEVELOPMENT: ${{ secrets.SATELLITE_ID_DEVELOPMENT }}
      SATELLITE_ID_PRODUCTION: ${{ secrets.SATELLITE_ID_PRODUCTION }}
      NODE_ENV: ${{ github.ref == 'refs/heads/deploy' && 'production' || 'development' }}
      JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: "https://registry.npmjs.org"
          
      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev typescript@5.4.2 @types/react@18.2.67 @types/node@20.11.30
        
      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SATELLITE_ID: ${{ github.ref == 'refs/heads/deploy' && secrets.SATELLITE_ID_PRODUCTION || secrets.SATELLITE_ID_DEVELOPMENT }}
          
      - name: Deploy to Internet Computer
        uses: junobuild/juno-action@main
        with:
          args: deploy ${{ github.ref == 'refs/heads/deploy' && '--network ic' || '--network local' }}
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}